SELECT 
        `p`.`id` AS `session_id`,
        `o`.`id` AS `observation_id`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`, '$.nom'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `session_name`,
        `pr`.`name` AS `protocole`,
        `p`.`mission_id` AS `mission_id`,
        `m`.`name` AS `mission_name`,
        `p`.`user_id` AS `user_id`,
        `u`.`username` AS `user_pseudo`,
        `p`.`observation_area_id` AS `site_id`,
        JSON_VALUE(`p`.`data`, '$.site.nom') AS `site_name`,
        st_y(`s`.`geodata`) AS latitude,
        st_x(`s`.`geodata`) AS longitude,
        `s`.`postcode` AS `site_zip_code`,
        `t1`.`title` AS `site_type`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`, '$.site.typeAutrePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `site_type_autre`,
        JSON_VALUE(`p`.`data`, '$.site.taille') AS `site_taille`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.site.compositions'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.site.compositions.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `site_compositions`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`,
                                '$.site.compositionsAutrePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `site_compositions_autre`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.site.arrosages'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.site.arrosages.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `site_arrosages`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`,
                                        '$.site.produitsPhytosanitaires'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.site.produits-phytosanitaires.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `site_produits_phyto`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.site.techniquesEntretien'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.site.techniques-entretien.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `site_techniques_entretien`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`,
                                '$.site.techniquesEntretienAutrePrecision'),
                        '
',
                        ' '),
                    '
                    ',
                    ' '),
                '	',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `site_techniques_entretien_autre`,
        JSON_VALUE(`p`.`data`,
                '$.site.anneeDernierChangementTerre') AS `site_anne_changement_terre`,
        JSON_VALUE(`p`.`data`, '$.dateDebut') AS `session_date`,
        JSON_VALUE(`p`.`data`, '$.heureDebutCollecte') AS `heure_collecte`,
        JSON_VALUE(`p`.`data`, '$.dateDernierePluie') AS `date_derniere_pluie`,
        `t2`.`title` AS `temperature`,
        `t3`.`title` AS `humidite_sol`,
        `t5`.`title` AS `profondeur`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.typesVegetation'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.types-vegetation.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `vegetations`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`,
                                '$.typesVegetationAutrePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `vegetations_autre`,
        JSON_VALUE(`p`.`data`, '$.zoneCultive') AS `zone_cultivee`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.couverturesSol'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.couvertures-sol.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `couvertures_sol`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`,
                                '$.couverturesSolAutrePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `couverture_sol_autre`,
        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(`p`.`data`, '$.typesResidusVegetaux'),
                                '[',
                                ''),
                            '"',
                            ''),
                        '","',
                        ';'),
                    'qubs.types-residus-vegetaux.',
                    ''),
                ']',
                ''),
            '-',
            ' ') AS `residus_vegetaux`,
        JSON_VALUE(`p`.`data`, '$.presenceOrganisme') AS `presence_organisme`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`,
                                '$.presenceOrganismeFalsePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `commentaires_presence_false`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`p`.`data`, '$.commentaire'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `commentaires_collecte`,
        CONCAT('https://www.qubs.fr/upload/medias/',
                `me1`.`name`) AS `url_photo_2m`,
        CONCAT('https://www.qubs.fr/upload/medias/',
                `me2`.`name`) AS `url_photo_installation`,
        CONCAT('https://www.qubs.fr/upload/medias/',
                `me3`.`name`) AS `url_photo_collecte`,
        `t4`.`title` AS `taxon`,
        IF(COUNT(IF(`c`.`model` = 'vote'
                    AND `c`.`deleted_at` IS NULL,
                1,
                NULL)) >= 3,
            1,
            0) AS `taxon_valide`,
        JSON_VALUE(`o`.`data`, '$.abondance') AS `taxon_count`,
        JSON_VALUE(`o`.`data`, '$.jeNePeuxPasCompter') AS `incomptable`,
        JSON_VALUE(`o`.`data`, '$.taxonJeNeSaisPas') AS `taxon_ne_sait_pas`,
        JSON_VALUE(`o`.`data`, '$.taxonPasDansLaListe') AS `taxon_pas_dans_liste`,
        CAST(REPLACE(REPLACE(REPLACE(JSON_VALUE(`o`.`data`,
                                '$.denominationPlusPreciseTruePrecision'),
                        '\r',
                        ' '),
                    '\n',
                    ' '),
                '\t',
                ' ')
            AS CHAR CHARSET UTF8MB3) AS `taxon_denomination_precision`,
        CONCAT('https://www.qubs.fr/upload/medias/',
                `me4`.`name`) AS `url_photo_taxon`
    FROM
        (((((((((((((((((((`qubs`.`participations` `p`
        JOIN `qubs`.`protocols` `pr` ON (`pr`.`id` = `p`.`protocol_id`))
        JOIN `qubs`.`users` `u` ON (`u`.`id` = `p`.`user_id`))
        JOIN `qubs`.`observation_areas` `s` ON (`s`.`id` = `p`.`observation_area_id`))
        LEFT JOIN `qubs`.`missions` `m` ON (`m`.`id` = `p`.`mission_id`))
        LEFT JOIN `qubs`.`thesaurus_values` `t1` ON (`t1`.`value` = JSON_VALUE(`p`.`data`, '$.site.type')))
        LEFT JOIN `qubs`.`thesaurus_values` `t2` ON (`t2`.`value` = JSON_VALUE(`p`.`data`, '$.temperature')))
        LEFT JOIN `qubs`.`thesaurus_values` `t3` ON (`t3`.`value` = JSON_VALUE(`p`.`data`, '$.humiditeSol')))
        LEFT JOIN `qubs`.`thesaurus_values` `t5` ON (`t5`.`value` = JSON_VALUE(`p`.`data`, '$.profondeur')))
        JOIN `qubs`.`participations_medias` `pm1` ON (`pm1`.`participation_id` = `p`.`id`
            AND `pm1`.`relation` = 'photo2Metres'))
        LEFT JOIN `qubs`.`medias` `me1` ON (`me1`.`id` = `pm1`.`media_id`))
        JOIN `qubs`.`participations_medias` `pm2` ON (`pm2`.`participation_id` = `p`.`id`
            AND `pm2`.`relation` = 'photoUp'))
        LEFT JOIN `qubs`.`medias` `me2` ON (`me2`.`id` = `pm2`.`media_id`))
        LEFT JOIN `qubs`.`participations_medias` `pm3` ON (`pm3`.`participation_id` = `p`.`id`
            AND `pm3`.`relation` = 'photoEnsemble'))
        LEFT JOIN `qubs`.`medias` `me3` ON (`me3`.`id` = `pm3`.`media_id`))
        LEFT JOIN `qubs`.`observations` `o` ON (`o`.`participation_id` = `p`.`id`))
        LEFT JOIN `qubs`.`thesaurus_values` `t4` ON (`t4`.`value` = JSON_VALUE(`o`.`data`, '$.taxon')))
        LEFT JOIN `qubs`.`observations_medias` `om1` ON (`om1`.`observation_id` = `o`.`id`))
        LEFT JOIN `qubs`.`medias` `me4` ON (`me4`.`id` = `om1`.`media_id`))
        LEFT JOIN `qubs`.`comments` `c` ON (`c`.`resource_id` = `o`.`id`
            AND `c`.`resource_type` = 'Observation'
            AND JSON_VALUE(`c`.`data`, '$.taxon') = JSON_VALUE(`o`.`data`, '$.taxon')))
    WHERE
        `p`.`deleted_at` IS NULL
            AND `o`.`deleted_at` IS NULL
            AND `p`.`protocol_id` = 2
    GROUP BY `p`.`id` , `o`.`id`
    ORDER BY `p`.`id`